package microwave

import (
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"go/types"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"golang.org/x/tools/go/packages"
)

// emit produces the formatted umbrella source bytes from the validated
// decl set. It also writes the result to cfg.Out on success.
func emit(cfg Config, decls []TaggedDecl, lookup map[string]string) ([]Diagnostic, error) {
	pkgPaths := collectPackages(decls)
	aliases := assignAliases(pkgPaths)

	var buf strings.Builder
	renderHeader(&buf, cfg)
	renderImports(&buf, aliases)

	byKind := groupDecls(decls)

	for _, d := range byKind[KindType] {
		renderType(&buf, d, aliases, lookup)
	}
	for _, d := range byKind[KindVar] {
		renderVar(&buf, d, aliases, lookup)
	}
	for _, d := range byKind[KindConst] {
		renderConst(&buf, d, aliases, lookup)
	}
	for _, d := range byKind[KindFunc] {
		renderFunc(&buf, d, aliases, lookup)
	}

	out, err := format.Source([]byte(buf.String()))
	if err != nil {
		return []Diagnostic{{
			Severity: SevError,
			Rule:     RuleEmitFormat,
			Pos:      token.Position{Filename: cfg.Out},
			Message:  fmt.Sprintf("internal: gofmt failed on emitted output: %v", err),
		}}, nil
	}

	if err := writeOutput(cfg.Out, out); err != nil {
		return nil, err
	}
	return nil, nil
}

// collectPackages walks every decl's AST and collects every package
// path that the emitted umbrella will need to import.
func collectPackages(decls []TaggedDecl) map[string]bool {
	set := map[string]bool{}
	for _, d := range decls {
		set[d.SourcePkg] = true
		switch d.Kind {
		case KindFunc:
			fd := d.Decl.(*ast.FuncDecl)
			walkExprPkgs(fd.Type, d.Pkg, set)
		case KindType:
			ts := d.Decl.(*ast.TypeSpec)
			if ts.TypeParams != nil {
				walkExprPkgs(ts.TypeParams, d.Pkg, set)
			}
		}
	}
	return set
}

// walkExprPkgs visits every Ident/SelectorExpr in node and adds the
// resolved package paths to set. Builtins and type parameters are
// skipped.
func walkExprPkgs(node ast.Node, pkg *packages.Package, set map[string]bool) {
	if node == nil {
		return
	}
	ast.Inspect(node, func(n ast.Node) bool {
		switch e := n.(type) {
		case *ast.SelectorExpr:
			if x, ok := e.X.(*ast.Ident); ok {
				if pn, ok := pkg.TypesInfo.Uses[x].(*types.PkgName); ok {
					set[pn.Imported().Path()] = true
					return false // do not descend further into pkg.Sel
				}
			}
		case *ast.Ident:
			obj := pkg.TypesInfo.Uses[e]
			if obj == nil {
				return true
			}
			if tn, ok := obj.(*types.TypeName); ok {
				if _, isTP := tn.Type().(*types.TypeParam); isTP {
					return true
				}
			}
			if obj.Pkg() != nil {
				set[obj.Pkg().Path()] = true
			}
		}
		return true
	})
}

// assignAliases produces a deterministic importPath -> alias map.
// Alias is the last path segment, lowercased; collisions are resolved
// by appending a numeric suffix in sorted-path order.
func assignAliases(pkgs map[string]bool) map[string]string {
	paths := make([]string, 0, len(pkgs))
	for p := range pkgs {
		paths = append(paths, p)
	}
	sort.Strings(paths)

	out := make(map[string]string, len(paths))
	used := map[string]int{}
	for _, p := range paths {
		base := strings.ToLower(lastSegment(p))
		base = sanitizeAlias(base)
		alias := base
		used[base]++
		if used[base] > 1 {
			alias = fmt.Sprintf("%s%d", base, used[base])
		}
		out[p] = alias
	}
	return out
}

func lastSegment(p string) string {
	i := strings.LastIndexAny(p, "/")
	if i < 0 {
		return p
	}
	return p[i+1:]
}

// sanitizeAlias replaces characters that aren't valid in a Go
// identifier with `_`, and prefixes a leading digit with `p`.
func sanitizeAlias(s string) string {
	if s == "" {
		return "pkg"
	}
	var b strings.Builder
	for i, r := range s {
		switch {
		case r == '_' || (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z'):
			b.WriteRune(r)
		case r >= '0' && r <= '9':
			if i == 0 {
				b.WriteRune('p')
			}
			b.WriteRune(r)
		default:
			b.WriteRune('_')
		}
	}
	return b.String()
}

func renderHeader(buf *strings.Builder, cfg Config) {
	buf.WriteString("// Code generated by microwave. DO NOT EDIT.\n\n")
	buf.WriteString("//go:generate microwave ")
	buf.WriteString(strings.Join(cfg.Args, " "))
	buf.WriteString("\n\n")
	buf.WriteString("package ")
	buf.WriteString(cfg.Pkg)
	buf.WriteString("\n\n")
}

func renderImports(buf *strings.Builder, aliases map[string]string) {
	if len(aliases) == 0 {
		return
	}
	paths := make([]string, 0, len(aliases))
	for p := range aliases {
		paths = append(paths, p)
	}
	sort.Strings(paths)
	buf.WriteString("import (\n")
	for _, p := range paths {
		fmt.Fprintf(buf, "\t%s %q\n", aliases[p], p)
	}
	buf.WriteString(")\n\n")
}

// groupDecls splits decls by Kind, sorting each group by EmitName for
// deterministic output.
func groupDecls(decls []TaggedDecl) map[Kind][]TaggedDecl {
	g := map[Kind][]TaggedDecl{}
	for _, d := range decls {
		g[d.Kind] = append(g[d.Kind], d)
	}
	for k := range g {
		sort.SliceStable(g[k], func(i, j int) bool {
			return g[k][i].EmitName < g[k][j].EmitName
		})
	}
	return g
}

func writeDoc(buf *strings.Builder, doc string) {
	if doc == "" {
		return
	}
	buf.WriteString(doc)
	if !strings.HasSuffix(doc, "\n") {
		buf.WriteString("\n")
	}
}

func renderType(buf *strings.Builder, d TaggedDecl, aliases, lookup map[string]string) {
	ts := d.Decl.(*ast.TypeSpec)
	alias := aliases[d.SourcePkg]

	writeDoc(buf, d.DocComment)
	buf.WriteString("type ")
	buf.WriteString(d.EmitName)

	if ts.TypeParams != nil && len(ts.TypeParams.List) > 0 {
		r := newRewriter(d.Pkg, aliases, lookup)
		buf.WriteString(r.renderTypeParams(ts.TypeParams))
		buf.WriteString(" = ")
		buf.WriteString(alias)
		buf.WriteString(".")
		buf.WriteString(d.SourceName)
		buf.WriteString(r.renderTypeParamArgs(ts.TypeParams))
	} else {
		buf.WriteString(" = ")
		buf.WriteString(alias)
		buf.WriteString(".")
		buf.WriteString(d.SourceName)
	}
	buf.WriteString("\n\n")
}

func renderVar(buf *strings.Builder, d TaggedDecl, aliases, lookup map[string]string) {
	alias := aliases[d.SourcePkg]
	writeDoc(buf, d.DocComment)
	fmt.Fprintf(buf, "var %s = %s.%s\n\n", d.EmitName, alias, d.SourceName)
	_ = lookup
}

func renderConst(buf *strings.Builder, d TaggedDecl, aliases, lookup map[string]string) {
	alias := aliases[d.SourcePkg]
	writeDoc(buf, d.DocComment)
	fmt.Fprintf(buf, "const %s = %s.%s\n\n", d.EmitName, alias, d.SourceName)
	_ = lookup
}

func renderFunc(buf *strings.Builder, d TaggedDecl, aliases, lookup map[string]string) {
	fd := d.Decl.(*ast.FuncDecl)
	alias := aliases[d.SourcePkg]
	r := newRewriter(d.Pkg, aliases, lookup)

	writeDoc(buf, d.DocComment)
	buf.WriteString("func ")
	buf.WriteString(d.EmitName)
	if fd.Type.TypeParams != nil && len(fd.Type.TypeParams.List) > 0 {
		buf.WriteString(r.renderTypeParams(fd.Type.TypeParams))
	}
	params, callArgs, variadic := r.renderParams(fd.Type.Params)
	buf.WriteString(params)

	resultPart, hasResults := r.renderResults(fd.Type.Results)
	if hasResults {
		buf.WriteString(" ")
		buf.WriteString(resultPart)
	}

	buf.WriteString(" { ")
	if hasResults {
		buf.WriteString("return ")
	}
	buf.WriteString(alias)
	buf.WriteString(".")
	buf.WriteString(d.SourceName)
	if fd.Type.TypeParams != nil && len(fd.Type.TypeParams.List) > 0 {
		buf.WriteString(r.renderTypeParamArgs(fd.Type.TypeParams))
	}
	buf.WriteString("(")
	buf.WriteString(callArgs)
	if variadic {
		buf.WriteString("...")
	}
	buf.WriteString(") }\n\n")
}

func writeOutput(out string, data []byte) error {
	abs, err := filepath.Abs(out)
	if err != nil {
		return fmt.Errorf("microwave: cannot resolve --out: %w", err)
	}
	return os.WriteFile(abs, data, 0o644)
}

// rewriter renders type expressions from one source package into Go
// source text suitable for the umbrella file. It rewrites references
// in two ways:
//   - identifiers whose source-qualified name is in the lookup map are
//     replaced with their umbrella emit name (no qualifier)
//   - other named types are qualified with the import alias the
//     umbrella has assigned to their declaring package
type rewriter struct {
	pkg     *packages.Package
	aliases map[string]string
	lookup  map[string]string
}

func newRewriter(pkg *packages.Package, aliases, lookup map[string]string) *rewriter {
	return &rewriter{pkg: pkg, aliases: aliases, lookup: lookup}
}

func (r *rewriter) renderType(expr ast.Expr) string {
	switch e := expr.(type) {
	case *ast.Ident:
		return r.renderIdent(e)
	case *ast.SelectorExpr:
		return r.renderSelector(e)
	case *ast.StarExpr:
		return "*" + r.renderType(e.X)
	case *ast.ArrayType:
		if e.Len == nil {
			return "[]" + r.renderType(e.Elt)
		}
		return "[" + r.renderType(e.Len) + "]" + r.renderType(e.Elt)
	case *ast.MapType:
		return "map[" + r.renderType(e.Key) + "]" + r.renderType(e.Value)
	case *ast.ChanType:
		switch e.Dir {
		case ast.SEND:
			return "chan<- " + r.renderType(e.Value)
		case ast.RECV:
			return "<-chan " + r.renderType(e.Value)
		default:
			return "chan " + r.renderType(e.Value)
		}
	case *ast.Ellipsis:
		return "..." + r.renderType(e.Elt)
	case *ast.FuncType:
		return r.renderFuncType(e)
	case *ast.IndexExpr:
		return r.renderType(e.X) + "[" + r.renderType(e.Index) + "]"
	case *ast.IndexListExpr:
		parts := make([]string, 0, len(e.Indices))
		for _, idx := range e.Indices {
			parts = append(parts, r.renderType(idx))
		}
		return r.renderType(e.X) + "[" + strings.Join(parts, ", ") + "]"
	case *ast.InterfaceType:
		return r.renderInterface(e)
	case *ast.StructType:
		return r.renderStruct(e)
	case *ast.BinaryExpr:
		return r.renderType(e.X) + " " + e.Op.String() + " " + r.renderType(e.Y)
	case *ast.UnaryExpr:
		return e.Op.String() + r.renderType(e.X)
	case *ast.ParenExpr:
		return "(" + r.renderType(e.X) + ")"
	case *ast.BasicLit:
		return e.Value
	}
	return ""
}

func (r *rewriter) renderIdent(e *ast.Ident) string {
	obj := r.pkg.TypesInfo.Uses[e]
	if obj == nil {
		obj = r.pkg.TypesInfo.Defs[e]
	}
	if obj == nil {
		return e.Name
	}
	if tn, ok := obj.(*types.TypeName); ok {
		if _, isTP := tn.Type().(*types.TypeParam); isTP {
			return e.Name
		}
	}
	if obj.Pkg() == nil {
		return e.Name
	}
	key := obj.Pkg().Path() + "." + e.Name
	if emit, ok := r.lookup[key]; ok {
		return emit
	}
	alias, ok := r.aliases[obj.Pkg().Path()]
	if !ok {
		return e.Name
	}
	return alias + "." + e.Name
}

func (r *rewriter) renderSelector(e *ast.SelectorExpr) string {
	if x, ok := e.X.(*ast.Ident); ok {
		if pn, ok := r.pkg.TypesInfo.Uses[x].(*types.PkgName); ok {
			path := pn.Imported().Path()
			key := path + "." + e.Sel.Name
			if emit, ok := r.lookup[key]; ok {
				return emit
			}
			alias := r.aliases[path]
			return alias + "." + e.Sel.Name
		}
	}
	return r.renderType(e.X) + "." + e.Sel.Name
}

func (r *rewriter) renderFuncType(ft *ast.FuncType) string {
	var b strings.Builder
	b.WriteString("func")
	b.WriteString(r.renderFieldList(ft.Params, true))
	if ft.Results != nil && len(ft.Results.List) > 0 {
		out, _ := r.renderResults(ft.Results)
		b.WriteString(" ")
		b.WriteString(out)
	}
	return b.String()
}

// renderFieldList formats a parenthesised field list. If withNames is
// false, names are dropped (used for return signatures rendered as just
// types).
func (r *rewriter) renderFieldList(fl *ast.FieldList, withNames bool) string {
	if fl == nil {
		return "()"
	}
	parts := make([]string, 0, len(fl.List))
	for _, f := range fl.List {
		ty := r.renderType(f.Type)
		if withNames && len(f.Names) > 0 {
			names := make([]string, 0, len(f.Names))
			for _, n := range f.Names {
				names = append(names, n.Name)
			}
			parts = append(parts, strings.Join(names, ", ")+" "+ty)
		} else {
			for i := 0; i < max(1, len(f.Names)); i++ {
				parts = append(parts, ty)
			}
		}
	}
	return "(" + strings.Join(parts, ", ") + ")"
}

// renderResults returns the Go-source rendering of a result list. The
// boolean reports whether the function has any results at all.
func (r *rewriter) renderResults(fl *ast.FieldList) (string, bool) {
	if fl == nil || len(fl.List) == 0 {
		return "", false
	}
	if len(fl.List) == 1 && len(fl.List[0].Names) == 0 {
		return r.renderType(fl.List[0].Type), true
	}
	return r.renderFieldList(fl, false), true
}

// renderInterface emits an interface literal. For v0 we expect this
// only in constraints (type sets); structural method sets in tagged
// signatures are unusual but handled.
func (r *rewriter) renderInterface(it *ast.InterfaceType) string {
	if it.Methods == nil || len(it.Methods.List) == 0 {
		return "interface{}"
	}
	parts := make([]string, 0, len(it.Methods.List))
	for _, f := range it.Methods.List {
		switch {
		case len(f.Names) > 0:
			ft := f.Type.(*ast.FuncType)
			parts = append(parts, f.Names[0].Name+r.renderFieldList(ft.Params, true)+resultsTail(r, ft.Results))
		default:
			parts = append(parts, r.renderType(f.Type))
		}
	}
	return "interface{ " + strings.Join(parts, "; ") + " }"
}

func resultsTail(r *rewriter, fl *ast.FieldList) string {
	out, ok := r.renderResults(fl)
	if !ok {
		return ""
	}
	return " " + out
}

func (r *rewriter) renderStruct(st *ast.StructType) string {
	if st.Fields == nil || len(st.Fields.List) == 0 {
		return "struct{}"
	}
	parts := make([]string, 0, len(st.Fields.List))
	for _, f := range st.Fields.List {
		ty := r.renderType(f.Type)
		if len(f.Names) == 0 {
			parts = append(parts, ty)
		} else {
			names := make([]string, 0, len(f.Names))
			for _, n := range f.Names {
				names = append(names, n.Name)
			}
			parts = append(parts, strings.Join(names, ", ")+" "+ty)
		}
	}
	return "struct{ " + strings.Join(parts, "; ") + " }"
}

// renderTypeParams emits a complete type-parameter clause, e.g.
// `[T any, U comparable]`. Constraints are rewritten via the rewriter.
func (r *rewriter) renderTypeParams(fl *ast.FieldList) string {
	parts := make([]string, 0, len(fl.List))
	for _, f := range fl.List {
		constraint := r.renderType(f.Type)
		names := make([]string, 0, len(f.Names))
		for _, n := range f.Names {
			names = append(names, n.Name)
		}
		parts = append(parts, strings.Join(names, ", ")+" "+constraint)
	}
	return "[" + strings.Join(parts, ", ") + "]"
}

// renderTypeParamArgs emits the bracketed list of type parameter
// identifiers used to instantiate the source type/func.
func (r *rewriter) renderTypeParamArgs(fl *ast.FieldList) string {
	names := make([]string, 0)
	for _, f := range fl.List {
		for _, n := range f.Names {
			names = append(names, n.Name)
		}
	}
	return "[" + strings.Join(names, ", ") + "]"
}

// renderParams emits the wrapper's parameter list and a comma-separated
// list of identifier names suitable for forwarding to the source func.
// Blank/duplicate names — and names that would shadow an import alias
// the wrapper's body relies on — are replaced with positional names
// p0, p1, ... The trailing bool reports whether the last parameter is
// variadic.
func (r *rewriter) renderParams(fl *ast.FieldList) (params string, callArgs string, variadic bool) {
	if fl == nil {
		return "()", "", false
	}

	reserved := map[string]bool{}
	for _, a := range r.aliases {
		reserved[a] = true
	}

	type one struct {
		name string
		typ  string
		varg bool
	}
	var flat []one

	used := map[string]int{}
	pos := 0
	for fi, f := range fl.List {
		isLast := fi == len(fl.List)-1
		_, isEllipsis := f.Type.(*ast.Ellipsis)

		names := f.Names
		count := max(1, len(names))
		for i := 0; i < count; i++ {
			var nm string
			if i < len(names) {
				nm = names[i].Name
			}
			if nm == "" || nm == "_" || used[nm] > 0 || reserved[nm] {
				nm = fmt.Sprintf("p%d", pos)
			}
			used[nm]++

			typ := r.renderType(f.Type)
			flat = append(flat, one{name: nm, typ: typ, varg: isEllipsis && isLast && i == count-1})
			pos++
		}
	}

	parts := make([]string, 0, len(flat))
	callParts := make([]string, 0, len(flat))
	for _, p := range flat {
		parts = append(parts, p.name+" "+p.typ)
		callParts = append(callParts, p.name)
		if p.varg {
			variadic = true
		}
	}
	return "(" + strings.Join(parts, ", ") + ")", strings.Join(callParts, ", "), variadic
}

// max returns the larger of a, b. Kept local to avoid pulling in
// generic stdlib helpers and so it inlines cleanly.
func max(a, b int) int {
	if a > b {
		return a
	}
	return b
}
