package microwave

import (
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"go/types"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"golang.org/x/tools/go/packages"
)

// emit produces the formatted umbrella source bytes from the validated
// decl set. It also writes the result to cfg.Out on success.
func emit(cfg Config, decls []TaggedDecl, lookup map[string]string) ([]Diagnostic, error) {
	natural := collectPackages(decls)
	chosen := assignAliases(natural)

	var buf strings.Builder
	renderHeader(&buf, cfg)
	renderImports(&buf, natural, chosen)
	renderBody(&buf, decls, natural, chosen, lookup)

	out, err := format.Source([]byte(buf.String()))
	if err != nil {
		return []Diagnostic{{
			Severity: SevError,
			Rule:     RuleEmitFormat,
			Pos:      token.Position{Filename: cfg.Out},
			Summary:  "gofmt failed on emitted output (internal bug)",
			Fields:   []Field{F("error", err.Error())},
		}}, nil
	}

	if err := writeOutput(cfg.Out, out); err != nil {
		return nil, err
	}
	return nil, nil
}

// collectPackages walks every decl's AST and returns the set of source
// packages that the umbrella file needs to reference. The map values
// are the packages' declared names (the identifier in their `package`
// clause); if not resolvable, an empty string is stored and resolved
// to the path's last segment by assignAliases.
func collectPackages(decls []TaggedDecl) map[string]string {
	out := map[string]string{}
	addPkg := func(path, name string) {
		if cur, ok := out[path]; !ok || cur == "" {
			out[path] = name
		}
	}

	for _, d := range decls {
		addPkg(d.SourcePkg, d.Pkg.Name)
		switch d.Kind {
		case KindFunc:
			fd := d.Decl.(*ast.FuncDecl)
			walkExprPkgs(fd.Type, d.Pkg, addPkg)
		case KindType:
			ts := d.Decl.(*ast.TypeSpec)
			if ts.TypeParams != nil {
				walkExprPkgs(ts.TypeParams, d.Pkg, addPkg)
			}
		}
	}
	return out
}

// walkExprPkgs visits every Ident/SelectorExpr in node and reports the
// resolved package path + declared package name to add. Builtins and
// type parameters are skipped.
func walkExprPkgs(node ast.Node, pkg *packages.Package, add func(path, name string)) {
	if node == nil {
		return
	}
	ast.Inspect(node, func(n ast.Node) bool {
		switch e := n.(type) {
		case *ast.SelectorExpr:
			if x, ok := e.X.(*ast.Ident); ok {
				if pn, ok := pkg.TypesInfo.Uses[x].(*types.PkgName); ok {
					imp := pn.Imported()
					add(imp.Path(), imp.Name())
					return false
				}
			}
		case *ast.Ident:
			obj := pkg.TypesInfo.Uses[e]
			if obj == nil {
				return true
			}
			if tn, ok := obj.(*types.TypeName); ok {
				if _, isTP := tn.Type().(*types.TypeParam); isTP {
					return true
				}
			}
			if obj.Pkg() != nil {
				add(obj.Pkg().Path(), obj.Pkg().Name())
			}
		}
		return true
	})
}

// assignAliases produces a deterministic importPath -> identifier map.
// The identifier equals the package's declared name when that name is
// unique across the set; collisions are resolved by appending a
// numeric suffix in sorted-path order.
func assignAliases(natural map[string]string) map[string]string {
	paths := make([]string, 0, len(natural))
	for p := range natural {
		paths = append(paths, p)
	}
	sort.Strings(paths)

	chosen := make(map[string]string, len(paths))
	count := map[string]int{}
	for _, p := range paths {
		base := natural[p]
		if base == "" {
			base = lastSegment(p)
		}
		base = sanitizeAlias(base)
		count[base]++
		if count[base] == 1 {
			chosen[p] = base
		} else {
			chosen[p] = fmt.Sprintf("%s%d", base, count[base])
		}
	}
	return chosen
}

func lastSegment(p string) string {
	i := strings.LastIndexAny(p, "/")
	if i < 0 {
		return p
	}
	return p[i+1:]
}

// sanitizeAlias replaces characters that aren't valid in a Go
// identifier with `_`, and prefixes a leading digit with `p`.
func sanitizeAlias(s string) string {
	if s == "" {
		return "pkg"
	}
	var b strings.Builder
	for i, r := range s {
		switch {
		case r == '_' || (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z'):
			b.WriteRune(r)
		case r >= '0' && r <= '9':
			if i == 0 {
				b.WriteRune('p')
			}
			b.WriteRune(r)
		default:
			b.WriteRune('_')
		}
	}
	return b.String()
}

func renderHeader(buf *strings.Builder, cfg Config) {
	buf.WriteString("// Code generated by microwave. DO NOT EDIT.\n\n")
	buf.WriteString("//go:generate microwave ")
	buf.WriteString(strings.Join(cfg.Args, " "))
	buf.WriteString("\n\n")
	buf.WriteString("package ")
	buf.WriteString(cfg.Pkg)
	buf.WriteString("\n\n")
}

// renderImports writes the import block. A bare `"path"` is used when
// the chosen identifier matches the package's declared name; otherwise
// an explicit `alias "path"` is emitted.
func renderImports(buf *strings.Builder, natural, chosen map[string]string) {
	if len(chosen) == 0 {
		return
	}
	paths := make([]string, 0, len(chosen))
	for p := range chosen {
		paths = append(paths, p)
	}
	sort.Strings(paths)
	buf.WriteString("import (\n")
	for _, p := range paths {
		if chosen[p] == natural[p] && natural[p] != "" {
			fmt.Fprintf(buf, "\t%q\n", p)
		} else {
			fmt.Fprintf(buf, "\t%s %q\n", chosen[p], p)
		}
	}
	buf.WriteString(")\n\n")
}

// renderBody emits one section per source package, sorted by the
// chosen identifier (case-insensitive). Within each section, all
// tagged decls are sorted by emit name (case-insensitive) regardless
// of kind. Each section begins with an `// === pkg ===` banner.
func renderBody(buf *strings.Builder, decls []TaggedDecl, natural, chosen, lookup map[string]string) {
	byPkg := map[string][]TaggedDecl{}
	for _, d := range decls {
		byPkg[d.SourcePkg] = append(byPkg[d.SourcePkg], d)
	}

	paths := make([]string, 0, len(byPkg))
	for p := range byPkg {
		paths = append(paths, p)
	}
	sort.SliceStable(paths, func(i, j int) bool {
		ai := strings.ToLower(chosen[paths[i]])
		aj := strings.ToLower(chosen[paths[j]])
		if ai != aj {
			return ai < aj
		}
		return paths[i] < paths[j]
	})

	for _, path := range paths {
		group := byPkg[path]
		sort.SliceStable(group, func(i, j int) bool {
			ni := strings.ToLower(group[i].EmitName)
			nj := strings.ToLower(group[j].EmitName)
			if ni != nj {
				return ni < nj
			}
			return group[i].EmitName < group[j].EmitName
		})

		writeBanner(buf, chosen[path])
		for _, d := range group {
			renderDecl(buf, d, natural, chosen, lookup)
		}
	}
}

// writeBanner emits an xp.go-style banner: a `// ===` rule above and
// below the package name, with the rule width matching the name.
func writeBanner(buf *strings.Builder, name string) {
	rule := strings.Repeat("=", len(name))
	fmt.Fprintf(buf, "// %s\n// %s\n// %s\n\n", rule, name, rule)
}

func renderDecl(buf *strings.Builder, d TaggedDecl, natural, chosen, lookup map[string]string) {
	switch d.Kind {
	case KindType:
		renderType(buf, d, chosen, lookup)
	case KindVar:
		renderVar(buf, d, chosen)
	case KindConst:
		renderConst(buf, d, chosen)
	case KindFunc:
		renderFunc(buf, d, chosen, lookup)
	}
	_ = natural
}

func writeDoc(buf *strings.Builder, doc string) {
	if doc == "" {
		return
	}
	buf.WriteString(doc)
	if !strings.HasSuffix(doc, "\n") {
		buf.WriteString("\n")
	}
}

func renderType(buf *strings.Builder, d TaggedDecl, chosen, lookup map[string]string) {
	ts := d.Decl.(*ast.TypeSpec)
	pkg := chosen[d.SourcePkg]

	writeDoc(buf, d.DocComment)
	buf.WriteString("type ")
	buf.WriteString(d.EmitName)

	if ts.TypeParams != nil && len(ts.TypeParams.List) > 0 {
		r := newRewriter(d.Pkg, chosen, lookup)
		buf.WriteString(r.renderTypeParams(ts.TypeParams))
		buf.WriteString(" = ")
		buf.WriteString(pkg)
		buf.WriteString(".")
		buf.WriteString(d.SourceName)
		buf.WriteString(r.renderTypeParamArgs(ts.TypeParams))
	} else {
		buf.WriteString(" = ")
		buf.WriteString(pkg)
		buf.WriteString(".")
		buf.WriteString(d.SourceName)
	}
	buf.WriteString("\n\n")
}

func renderVar(buf *strings.Builder, d TaggedDecl, chosen map[string]string) {
	writeDoc(buf, d.DocComment)
	fmt.Fprintf(buf, "var %s = %s.%s\n\n", d.EmitName, chosen[d.SourcePkg], d.SourceName)
}

func renderConst(buf *strings.Builder, d TaggedDecl, chosen map[string]string) {
	writeDoc(buf, d.DocComment)
	fmt.Fprintf(buf, "const %s = %s.%s\n\n", d.EmitName, chosen[d.SourcePkg], d.SourceName)
}

func renderFunc(buf *strings.Builder, d TaggedDecl, chosen, lookup map[string]string) {
	fd := d.Decl.(*ast.FuncDecl)
	pkg := chosen[d.SourcePkg]
	r := newRewriter(d.Pkg, chosen, lookup)

	writeDoc(buf, d.DocComment)
	buf.WriteString("func ")
	buf.WriteString(d.EmitName)
	hasTypeParams := fd.Type.TypeParams != nil && len(fd.Type.TypeParams.List) > 0
	if hasTypeParams {
		buf.WriteString(r.renderTypeParams(fd.Type.TypeParams))
	}
	params, callArgs, variadic := r.renderParams(fd.Type.Params)
	buf.WriteString(params)

	resultPart, hasResults := r.renderResults(fd.Type.Results)
	if hasResults {
		buf.WriteString(" ")
		buf.WriteString(resultPart)
	}

	buf.WriteString(" { ")
	if hasResults {
		buf.WriteString("return ")
	}
	buf.WriteString(pkg)
	buf.WriteString(".")
	buf.WriteString(d.SourceName)
	if hasTypeParams && !typeArgsInferable(fd.Type) {
		buf.WriteString(r.renderTypeParamArgs(fd.Type.TypeParams))
	}
	buf.WriteString("(")
	buf.WriteString(callArgs)
	if variadic {
		buf.WriteString("...")
	}
	buf.WriteString(") }\n\n")
}

// typeArgsInferable reports whether the source func's type parameters
// can all be inferred at the call site from the argument types alone.
// True iff every declared type-parameter name appears at least once
// inside one of the function's parameter type expressions.
//
// When this holds, the wrapper body can call `pkg.F(args...)` and Go
// will infer the type args. Otherwise the wrapper must spell them out
// as `pkg.F[T1, T2, ...](args...)` — typically when a type param
// appears only in the result type.
func typeArgsInferable(ft *ast.FuncType) bool {
	if ft.TypeParams == nil || len(ft.TypeParams.List) == 0 {
		return true
	}
	declared := map[string]bool{}
	for _, f := range ft.TypeParams.List {
		for _, n := range f.Names {
			declared[n.Name] = true
		}
	}
	if ft.Params == nil {
		return len(declared) == 0
	}
	seen := map[string]bool{}
	for _, f := range ft.Params.List {
		ast.Inspect(f.Type, func(n ast.Node) bool {
			if id, ok := n.(*ast.Ident); ok && declared[id.Name] {
				seen[id.Name] = true
			}
			return true
		})
	}
	return len(seen) == len(declared)
}

func writeOutput(out string, data []byte) error {
	abs, err := filepath.Abs(out)
	if err != nil {
		return fmt.Errorf("microwave: cannot resolve --out: %w", err)
	}
	return os.WriteFile(abs, data, 0o644)
}

// rewriter renders type expressions from one source package into Go
// source text suitable for the umbrella file. It rewrites references
// in two ways:
//   - identifiers whose source-qualified name is in the lookup map are
//     replaced with their umbrella emit name (no qualifier)
//   - other named types are qualified with the chosen identifier the
//     umbrella has assigned to their declaring package
type rewriter struct {
	pkg    *packages.Package
	chosen map[string]string
	lookup map[string]string
}

func newRewriter(pkg *packages.Package, chosen, lookup map[string]string) *rewriter {
	return &rewriter{pkg: pkg, chosen: chosen, lookup: lookup}
}

func (r *rewriter) renderType(expr ast.Expr) string {
	switch e := expr.(type) {
	case *ast.Ident:
		return r.renderIdent(e)
	case *ast.SelectorExpr:
		return r.renderSelector(e)
	case *ast.StarExpr:
		return "*" + r.renderType(e.X)
	case *ast.ArrayType:
		if e.Len == nil {
			return "[]" + r.renderType(e.Elt)
		}
		return "[" + r.renderType(e.Len) + "]" + r.renderType(e.Elt)
	case *ast.MapType:
		return "map[" + r.renderType(e.Key) + "]" + r.renderType(e.Value)
	case *ast.ChanType:
		switch e.Dir {
		case ast.SEND:
			return "chan<- " + r.renderType(e.Value)
		case ast.RECV:
			return "<-chan " + r.renderType(e.Value)
		default:
			return "chan " + r.renderType(e.Value)
		}
	case *ast.Ellipsis:
		return "..." + r.renderType(e.Elt)
	case *ast.FuncType:
		return r.renderFuncType(e)
	case *ast.IndexExpr:
		return r.renderType(e.X) + "[" + r.renderType(e.Index) + "]"
	case *ast.IndexListExpr:
		parts := make([]string, 0, len(e.Indices))
		for _, idx := range e.Indices {
			parts = append(parts, r.renderType(idx))
		}
		return r.renderType(e.X) + "[" + strings.Join(parts, ", ") + "]"
	case *ast.InterfaceType:
		return r.renderInterface(e)
	case *ast.StructType:
		return r.renderStruct(e)
	case *ast.BinaryExpr:
		return r.renderType(e.X) + " " + e.Op.String() + " " + r.renderType(e.Y)
	case *ast.UnaryExpr:
		return e.Op.String() + r.renderType(e.X)
	case *ast.ParenExpr:
		return "(" + r.renderType(e.X) + ")"
	case *ast.BasicLit:
		return e.Value
	}
	return ""
}

func (r *rewriter) renderIdent(e *ast.Ident) string {
	obj := r.pkg.TypesInfo.Uses[e]
	if obj == nil {
		obj = r.pkg.TypesInfo.Defs[e]
	}
	if obj == nil {
		return e.Name
	}
	if tn, ok := obj.(*types.TypeName); ok {
		if _, isTP := tn.Type().(*types.TypeParam); isTP {
			return e.Name
		}
	}
	if obj.Pkg() == nil {
		return e.Name
	}
	key := obj.Pkg().Path() + "." + e.Name
	if emit, ok := r.lookup[key]; ok {
		return emit
	}
	alias, ok := r.chosen[obj.Pkg().Path()]
	if !ok {
		return e.Name
	}
	return alias + "." + e.Name
}

func (r *rewriter) renderSelector(e *ast.SelectorExpr) string {
	if x, ok := e.X.(*ast.Ident); ok {
		if pn, ok := r.pkg.TypesInfo.Uses[x].(*types.PkgName); ok {
			path := pn.Imported().Path()
			key := path + "." + e.Sel.Name
			if emit, ok := r.lookup[key]; ok {
				return emit
			}
			alias := r.chosen[path]
			return alias + "." + e.Sel.Name
		}
	}
	return r.renderType(e.X) + "." + e.Sel.Name
}

func (r *rewriter) renderFuncType(ft *ast.FuncType) string {
	var b strings.Builder
	b.WriteString("func")
	b.WriteString(r.renderFieldList(ft.Params, true))
	if ft.Results != nil && len(ft.Results.List) > 0 {
		out, _ := r.renderResults(ft.Results)
		b.WriteString(" ")
		b.WriteString(out)
	}
	return b.String()
}

func (r *rewriter) renderFieldList(fl *ast.FieldList, withNames bool) string {
	if fl == nil {
		return "()"
	}
	parts := make([]string, 0, len(fl.List))
	for _, f := range fl.List {
		ty := r.renderType(f.Type)
		if withNames && len(f.Names) > 0 {
			names := make([]string, 0, len(f.Names))
			for _, n := range f.Names {
				names = append(names, n.Name)
			}
			parts = append(parts, strings.Join(names, ", ")+" "+ty)
		} else {
			for i := 0; i < max(1, len(f.Names)); i++ {
				parts = append(parts, ty)
			}
		}
	}
	return "(" + strings.Join(parts, ", ") + ")"
}

func (r *rewriter) renderResults(fl *ast.FieldList) (string, bool) {
	if fl == nil || len(fl.List) == 0 {
		return "", false
	}
	if len(fl.List) == 1 && len(fl.List[0].Names) == 0 {
		return r.renderType(fl.List[0].Type), true
	}
	return r.renderFieldList(fl, false), true
}

func (r *rewriter) renderInterface(it *ast.InterfaceType) string {
	if it.Methods == nil || len(it.Methods.List) == 0 {
		return "interface{}"
	}
	parts := make([]string, 0, len(it.Methods.List))
	for _, f := range it.Methods.List {
		switch {
		case len(f.Names) > 0:
			ft := f.Type.(*ast.FuncType)
			parts = append(parts, f.Names[0].Name+r.renderFieldList(ft.Params, true)+resultsTail(r, ft.Results))
		default:
			parts = append(parts, r.renderType(f.Type))
		}
	}
	return "interface{ " + strings.Join(parts, "; ") + " }"
}

func resultsTail(r *rewriter, fl *ast.FieldList) string {
	out, ok := r.renderResults(fl)
	if !ok {
		return ""
	}
	return " " + out
}

func (r *rewriter) renderStruct(st *ast.StructType) string {
	if st.Fields == nil || len(st.Fields.List) == 0 {
		return "struct{}"
	}
	parts := make([]string, 0, len(st.Fields.List))
	for _, f := range st.Fields.List {
		ty := r.renderType(f.Type)
		if len(f.Names) == 0 {
			parts = append(parts, ty)
		} else {
			names := make([]string, 0, len(f.Names))
			for _, n := range f.Names {
				names = append(names, n.Name)
			}
			parts = append(parts, strings.Join(names, ", ")+" "+ty)
		}
	}
	return "struct{ " + strings.Join(parts, "; ") + " }"
}

func (r *rewriter) renderTypeParams(fl *ast.FieldList) string {
	parts := make([]string, 0, len(fl.List))
	for _, f := range fl.List {
		constraint := r.renderType(f.Type)
		names := make([]string, 0, len(f.Names))
		for _, n := range f.Names {
			names = append(names, n.Name)
		}
		parts = append(parts, strings.Join(names, ", ")+" "+constraint)
	}
	return "[" + strings.Join(parts, ", ") + "]"
}

func (r *rewriter) renderTypeParamArgs(fl *ast.FieldList) string {
	names := make([]string, 0)
	for _, f := range fl.List {
		for _, n := range f.Names {
			names = append(names, n.Name)
		}
	}
	return "[" + strings.Join(names, ", ") + "]"
}

// renderParams emits the wrapper's parameter list and a comma-separated
// list of identifier names suitable for forwarding to the source func.
// Blank/duplicate names — and names that would shadow a package
// identifier the wrapper's body relies on — are replaced with
// positional names p0, p1, ...
func (r *rewriter) renderParams(fl *ast.FieldList) (params string, callArgs string, variadic bool) {
	if fl == nil {
		return "()", "", false
	}

	reserved := map[string]bool{}
	for _, a := range r.chosen {
		reserved[a] = true
	}

	type one struct {
		name string
		typ  string
		varg bool
	}
	var flat []one

	used := map[string]int{}
	pos := 0
	for fi, f := range fl.List {
		isLast := fi == len(fl.List)-1
		_, isEllipsis := f.Type.(*ast.Ellipsis)

		names := f.Names
		count := max(1, len(names))
		for i := 0; i < count; i++ {
			var nm string
			if i < len(names) {
				nm = names[i].Name
			}
			if nm == "" || nm == "_" || used[nm] > 0 || reserved[nm] {
				nm = fmt.Sprintf("p%d", pos)
			}
			used[nm]++

			typ := r.renderType(f.Type)
			flat = append(flat, one{name: nm, typ: typ, varg: isEllipsis && isLast && i == count-1})
			pos++
		}
	}

	parts := make([]string, 0, len(flat))
	callParts := make([]string, 0, len(flat))
	for _, p := range flat {
		parts = append(parts, p.name+" "+p.typ)
		callParts = append(callParts, p.name)
		if p.varg {
			variadic = true
		}
	}
	return "(" + strings.Join(parts, ", ") + ")", strings.Join(callParts, ", "), variadic
}

func max(a, b int) int {
	if a > b {
		return a
	}
	return b
}
